# Generated by Django 4.0.1 on 2022-08-29 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('delivery', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('transport', 'transport'), ('invoiced', 'invoiced')], default='transport', max_length=50)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaomi.xiaomi')),
            ],
        ),
    ]
