# Generated by Django 4.0.1 on 2022-08-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0002_remove_status_delivery_xiaomi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='transport', max_length=50),
        ),
    ]
