# Generated by Django 4.0.1 on 2022-08-29 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0003_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='xiaomi',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaomi.status'),
        ),
    ]
