# Generated by Django 4.0.1 on 2022-09-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0005_xiaomi_creator_xiaomi_delivery_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomi',
            name='delivery_file',
            field=models.FileField(upload_to='xiaomi/deliveries'),
        ),
    ]
