# Generated by Django 4.0.1 on 2022-09-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0006_alter_xiaomi_delivery_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xiaomi',
            name='creator',
        ),
    ]
