# Generated by Django 4.0.1 on 2022-09-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0012_alter_xiaomi_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xiaomi',
            old_name='id',
            new_name='delivery_id',
        ),
    ]
