# Generated by Django 4.0.1 on 2022-09-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0015_remove_xiaomi_creator_remove_xiaomi_delivery_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xiaomi',
            old_name='delivery_id',
            new_name='id',
        ),
    ]
