# Generated by Django 4.0.1 on 2022-09-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0019_xiaomiclaimparts_xiaomipartscatalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaomiclaimparts',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Claimed', 'Claimed')], default='Waiting', max_length=50),
        ),
    ]
