# Generated by Django 4.0.1 on 2022-09-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0021_xiaomi_reckoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomi',
            name='reckoning',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
