# Generated by Django 4.0.1 on 2022-09-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0023_alter_xiaomi_reckoning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xiaomi',
            name='reckoning',
        ),
    ]
