# Generated by Django 4.0.1 on 2022-09-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0025_xiaomi_reckoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomipartscatalog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
