# Generated by Django 4.0.1 on 2022-09-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0026_alter_xiaomipartscatalog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xiaomi',
            name='status',
        ),
        migrations.AddField(
            model_name='xiaomi',
            name='status',
            field=models.ManyToManyField(default='Transport', to='xiaomi.Status'),
        ),
    ]
