# Generated by Django 4.0.1 on 2022-09-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0027_remove_xiaomi_status_xiaomi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xiaomi',
            name='status',
        ),
        migrations.AddField(
            model_name='xiaomi',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaomi.status'),
        ),
    ]
