# Generated by Django 4.0.1 on 2022-09-19 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0030_xiaomi_zz_pmgh_xiaomi_zz_pmgp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPmgh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pmgh', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPmgp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pmgp', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='xiaomi',
            name='status_pmgh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xiaomi.statuspmgh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xiaomi',
            name='status_pmgp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xiaomi.statuspmgp'),
            preserve_default=False,
        ),
    ]
