# Generated by Django 4.0.1 on 2022-09-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0031_statuspmgh_statuspmgp_xiaomi_status_pmgh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomi',
            name='status_pmgh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xiaomi.statuspmgh'),
        ),
        migrations.AlterField(
            model_name='xiaomi',
            name='status_pmgp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xiaomi.statuspmgp'),
        ),
    ]
