# Generated by Django 4.0.1 on 2022-09-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0032_alter_xiaomi_status_pmgh_alter_xiaomi_status_pmgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaomi',
            name='lpr_pmgh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xiaomi',
            name='lpr_pmgp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
