# Generated by Django 4.0.1 on 2022-09-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0033_xiaomi_lpr_pmgh_xiaomi_lpr_pmgp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaomi',
            name='lpr_pmgh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xiaomi',
            name='lpr_pmgp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
