# Generated by Django 4.1.2 on 2022-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0034_alter_xiaomi_lpr_pmgh_alter_xiaomi_lpr_pmgp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailReportReceivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
