# Generated by Django 4.1.2 on 2022-10-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0035_mailreportreceivers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xiaomi',
            options={'ordering': ['-date']},
        ),
    ]
