# Generated by Django 5.0.1 on 2024-02-25 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0036_alter_xiaomi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_number', models.CharField(max_length=50, unique=True)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('part_description', models.CharField(blank=True, max_length=200, null=True)),
                ('part_qty', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
