# Generated by Django 5.0.1 on 2024-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0037_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
