# Generated by Django 5.0.1 on 2024-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi', '0038_alter_delivery_delivery_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='xiaomi/deliveries/'),
        ),
    ]
