# Generated by Django 5.0.6 on 2024-06-12 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(db_column='SO Number', max_length=50)),
                ('parts_number', models.CharField(blank=True, db_column='Parts Number', max_length=50, null=True)),
                ('parts_description', models.CharField(blank=True, db_column='Parts Desciption', max_length=200, null=True)),
                ('qty', models.IntegerField(db_column='qty', null=True)),
            ],
            options={
                'ordering': ['-qty'],
            },
        ),
        migrations.CreateModel(
            name='MailReportReceivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PartsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_number', models.CharField(blank=True, db_column='Kod pozycji', max_length=50, null=True)),
                ('parts_description', models.CharField(blank=True, db_column='Opis dla serwisu', max_length=200, null=True)),
                ('warehouse', models.CharField(blank=True, db_column='Domyślny magazyn serwisu', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPmgh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pmgh', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPmgp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pmgp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingsDetails',
            fields=[
                ('parts_number', models.CharField(blank=True, db_column='Parts Number', max_length=50, null=True)),
                ('qty', models.IntegerField(db_column='Waiting', null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-qty'],
            },
        ),
        migrations.CreateModel(
            name='XiaomiClaimParts',
            fields=[
                ('claim_part', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Claimed', 'Claimed')], default='Waiting', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='XiaomiPartsCatalog',
            fields=[
                ('parts_catalog', models.CharField(default='Parts Catalog', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='xiaomi/parts-catalog/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='XiaomiWaitingParts',
            fields=[
                ('waiting_parts', models.CharField(default='Waiting Parts', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='xiaomi/waiting-parts/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('delivery', models.CharField(max_length=50, unique=True)),
                ('reckoning', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('zz_pmgp', models.CharField(blank=True, max_length=50, null=True)),
                ('lpr_pmgp', models.CharField(blank=True, max_length=100, null=True)),
                ('zz_pmgh', models.CharField(blank=True, max_length=50, null=True)),
                ('lpr_pmgh', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='xiaomi/deliveries/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maitrox.status')),
                ('status_pmgh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maitrox.statuspmgh')),
                ('status_pmgp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maitrox.statuspmgp')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
