# Generated by Django 5.0.6 on 2024-07-11 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maitrox', '0002_alter_partsdetails_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XiaomiClaimParts',
            new_name='ClaimParts',
        ),
        migrations.RenameModel(
            old_name='Xiaomi',
            new_name='Maitrox',
        ),
        migrations.RenameModel(
            old_name='XiaomiPartsCatalog',
            new_name='PartsCatalog',
        ),
        migrations.RenameModel(
            old_name='XiaomiWaitingParts',
            new_name='WaitingParts',
        ),
        migrations.AlterField(
            model_name='maitrox',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maitrox.status'),
        ),
        migrations.AlterField(
            model_name='maitrox',
            name='status_pmgh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maitrox.statuspmgh'),
        ),
        migrations.AlterField(
            model_name='maitrox',
            name='status_pmgp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maitrox.statuspmgp'),
        ),
    ]
