from django.urls import path
from . import views

urlpatterns = [
    path("pulpit-dostaw/", views.MaitroxView.as_view(),
         name="maitrox"),
    path("dostawa/<str:pk>/", views.MaitroxDeliveryDetails.as_view(), 
         name="maitrox_delivery"),
    path("wszystkie-dostawy/", views.MaitroxDeliveries.as_view(), 
         name="maitrox_deliveries"),
     path("nowa-dostawa/", views.MaitroxDeliveryCreate.as_view(), 
         name="maitrox_delivery_create"),
    path("edycja-dostawy/<str:pk>/", views.MaitroxDeliveryUpdate.as_view(), 
         name="maitrox_delivery_update"),
    path("edycja-pliku-dostawy/<str:pk>/", views.MaitroxFileUpdate.as_view(),
         name="maitrox_delivery_file_update"),
    path("usun-dostawe/<str:pk>/", views.MaitroxDeliveryDelete.as_view(),
         name="maitrox_delivery_delete"),
    path("raport-dostaw/", views.MaitroxDeliveryReport.as_view(),
         name="maitrox_delivery_report"),
    
    path("dodaj-katalog-czesci/", views.MaitroxPartsNew.as_view(), 
         name="maitrox_parts_new"),
    path("katalog-czesci/", views.MaitroxPartsAll.as_view(), 
         name="maitrox_parts_all"),    
    path("czesci-katalog/", views.MaitroxParts.as_view(),
         name="maitrox_parts"),
    path("edycja-katalogu-czesci/<str:pk>/", views.MaitroxPartsUpdate.as_view(),
         name="maitrox_parts_update"),
    
    path("rejestr-reklamacji/", views.MaitroxClaims.as_view(),
         name="maitrox_claims"),
    path("nowa-reklamacja/", views.MaitroxClaimsCreate.as_view(),
         name="maitrox_claims_new"),
    path("edycja-reklamacji/<str:pk>/", views.MaitroxClaimsUpdate.as_view(),
         name="maitrox_claims_update"),
    path("usun-reklamacje/<str:pk>/", views.MaitroxClaimsDelete.as_view(),
         name="maitrox_claims_delete"),
    
    path("dodaj-plik-czekajacych/", views.MaitroxWaitingCreate.as_view(), 
        name="maitrox_waiting_new"),
    path("pliki-czekajacych/", views.MaitroxWaitingsAll.as_view(), 
        name="maitrox_waiting_all"),
    path("czesci-czekajace/", views.MaitroxWaitings.as_view(), 
        name="maitrox_waiting"),
    path("edycja-pliku-czekajacych/<str:pk>/", views.MaitroxWaitingsUpdate.as_view(),
         name="maitrox_waiting_update"),
]