# Generated by Django 4.1.6 on 2023-02-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NrNaprawy', models.CharField(max_length=30)),
                ('DataRejestracji', models.DateField()),
                ('TypZgloszenia', models.CharField(max_length=255)),
                ('Roszczenie', models.CharField(max_length=255)),
                ('ReklamacjaCCS', models.IntegerField()),
                ('Producent', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=255)),
                ('KodPozycji', models.CharField(max_length=20)),
                ('KodPozycjiNazwa', models.CharField(max_length=90)),
                ('KodPozycjiTypNaprawy', models.CharField(max_length=255)),
                ('StatusWiersza', models.CharField(max_length=255)),
                ('DataUtworzeniaWiersza', models.DateTimeField()),
                ('Ilosc', models.IntegerField()),
            ],
        ),
    ]
