# Generated by Django 4.1.6 on 2023-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_djangoreport_delete_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZamowienieZakupu', models.CharField(max_length=25)),
                ('Oddzial', models.CharField(max_length=10)),
                ('Magazyn', models.CharField(max_length=25)),
                ('OdwolanieDoDostawcy', models.CharField(max_length=120)),
                ('Stan', models.CharField(max_length=255, null=True)),
                ('Status', models.CharField(max_length=255, null=True)),
                ('KontoDostawcy', models.CharField(max_length=20)),
                ('NazwaDostawcy', models.CharField(max_length=120)),
                ('DataUtworzeniaG', models.DateTimeField(null=True)),
                ('KodPozycji', models.CharField(max_length=20)),
                ('KodPozycjiNazwa', models.CharField(max_length=90, null=True)),
                ('Ilosc', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'django].[vv_ZamowieniaZakupu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogisticWaiting',
            fields=[
                ('DataGenerowania', models.DateTimeField(primary_key=True, serialize=False)),
                ('NrNaprawy', models.CharField(max_length=30)),
                ('DataRejestracji', models.DateField(null=True)),
                ('TypZgloszenia', models.CharField(max_length=255, null=True)),
                ('Roszczenie', models.CharField(max_length=255, null=True)),
                ('ReklamacjaCCS', models.IntegerField(null=True)),
                ('Producent', models.CharField(max_length=255, null=True)),
                ('Model', models.CharField(max_length=20, null=True)),
                ('Status', models.CharField(max_length=255, null=True)),
                ('KodPozycji', models.CharField(max_length=20, null=True)),
                ('KodPozycjiNazwa', models.CharField(max_length=90, null=True)),
                ('KodPozycjiTypNaprawy', models.CharField(max_length=255, null=True)),
                ('StatusWiersza', models.CharField(max_length=255, null=True)),
                ('DataUtworzeniaWiersza', models.DateTimeField(null=True)),
                ('Ilosc', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'django].[vv_Rpt060_LogistykaCzekajace',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoReport',
        ),
    ]
