# Generated by Django 5.0.1 on 2024-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_buyingorder_logisticwaiting_delete_djangoreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replacements',
            fields=[
                ('KodPozycji', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Zamiennik', models.CharField(max_length=20)),
                ('Glowny', models.IntegerField()),
            ],
            options={
                'db_table': 'django].[vv_Pozycje',
                'managed': False,
            },
        ),
    ]
